name: WolfBeat
description: Listen to your songs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  mobx: ^1.2.1+2
  flutter_mobx: ^1.0.0

  # Dependency injection
  get_it: ^4.0.4

  # User interface
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.8.1
  hexcolor: ^1.0.4

  # Player
  audioplayers: ^0.15.1
  
  # Firebase
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6

  # Services
  google_sign_in: ^4.5.1
  image_picker: ^0.6.7+4
  
dev_dependencies:
  # Linter
  effective_dart: ^1.2.4

  # Codegen for MobX
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.0+1

  # Tests
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
  - family: SourceSansPro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf
      weight: 400
    - asset: fonts/SourceSansPro-SemiBold.ttf
      weight: 600
    - asset: fonts/SourceSansPro-Bold.ttf
      weight: 700

  assets:
    - assets/fallback/